src-git packages https://github.com/openwrt/packages.git^50add41033180a0f00813493bd205aa236acfe17
src-git luci https://github.com/openwrt/luci.git^183ab68aef71beedac346d664876c188e9c9fdcc
src-git routing https://github.com/openwrt/routing.git^d53907107d48331ef38978f7a259bc8eac3765a0
src-cpy imagestream ../opuntia_imagestream
