src-git packages https://github.com/openwrt/packages.git^c919fddfc1b4c886a00271a4c46d6ab40f6dc77a
src-git luci https://github.com/openwrt/luci.git^d90728d2c05da46fe5c2a1a1100a93f9a55730d7
src-git routing https://github.com/openwrt/routing.git^0ff4ab0506f2ab09b829699bef6b8be8bf8f87f1
src-cpy imagestream ../opuntia_imagestream
